### ISSUE TITLE
Helper functions for anwering questions

### ISSUE THREAD

**Issue by LRKer** [692-Team-1-NLP/proj-1#16]
wrote get_det(), get_perp(), get_occur(), get_co_occur() functions for answering questions. adding one book at a time, so feel free to add index==whichever book you're working on to each function as you go.

**Comment by LRKer** [comment]
added get_context() function so you can see what's going on in neighboring sentences.

**Comment by AddiMT** [comment]
Sounds good.

**Comment by AddiMT** [comment]
Done
