### ISSUE TITLE
question 4: context around perpetrator - ask begoli 

### ISSUE THREAD

**Issue by LRKer** [692-Team-1-NLP/proj-1#20]
Asking Begoli about question 4 "three words around perpetrator at each mention". We have 80 mentions in first book, don't want to report all unless we have to. asking him if he wants all of them or just first 5 or so.

**Comment by LRKer** [comment]
writing function to get context programatically. Is complicated by fact that we put sentences in chapters so next word might be in next chapter, so have to check if next word in next sentence in next chapter. ugly function, but working - still testing

**Comment by LRKer** [comment]
note; the earlier context function I wrote simply returns sentences -1 , sentence, sentence+1. this version gets words-3...words+3 and, assuming I did it correctly, accounts for when next/previous words span chapter gaps

**Comment by AddiMT** [comment]
Lets discuss this more when we meet

**Comment by AddiMT** [comment]
Done, in the notebook
