### ISSUE TITLE
Complete Data Cleaning Cell in ipynb

### ISSUE THREAD

**Issue by AddiMT** [692-Team-1-NLP/proj-1#6]

**Comment by verolero86** [comment]
Some notes on things that we may need to clean-up:

- Ends of line 
- Carriage returns
- Hair spaces (`\u200a`)
- Regular spaces
- Tabs

All of these are captured by `\s`.

We also may want to clean up contractions to be full words (e.g., "don't" to "do not"), and potentially change case to lowercase.

**Comment by verolero86** [comment]
In some cases, there is no break between the word at the end of a chapter line and the next word, so removing EOL characters should probably be a substitution with a space instead.

**Comment by verolero86** [comment]
More clean-up from lecture in addition to above: replace numbers, remove punctuation

**Comment by verolero86** [comment]
Summary of above:

- [x] Remove (or replace) subset of white spaces
- [x] Switch to lowercase
- [ ] Replace numbers
- [ ] Replace contractions
- [ ] Remove punctuation (do we do this afterwards or maybe not at all?)

**Comment by LRKer** [comment]
incorporated veronica's white space removal and lowercase into my corpus builder. so running get_corpus and clean_corpus yields a regex-ready final product
