### ISSUE TITLE
figure out how to track chapters and sentence numbers to chapters for analysis

### ISSUE THREAD

**Issue by AddiMT** [692-Team-1-NLP/proj-1#8]

**Comment by LRKer** [comment]
tested code for carving chapters out of first novel "Murder on the Links" that uses "1 Name of chapter" format. will do other chapter format next. waiting to hear from begoli about sentence splitting

**Comment by LRKer** [comment]
chapter carving complete. corpus is dictionary of books where each book is a dict of 3 dicts (content, chapters, title)

**Comment by AddiMT** [comment]
since, this is complete, closing it now
